### ISSUE TITLE
explode(): Passing null to parameter #2 ($string) of type string is deprecated

### ISSUE THREAD

**Issue by Koala** [alexplusde/neues#16]
Der Aufruf von Aktuelles bringt mir eine Fehlermeldung aber keinen Whoops.
Das scheint aber ein reines YFom* Problem zu sein.  Der Fehler kommt auch, wenn ich im YForm Tablemanager versuche die Daten der Tabelle News aufzurufen.

```
explode(): Passing null to parameter #2 ($string) of type string is deprecated
#0 [internal function]: rex_error_handler::handleError()
#1 /usr/local/www/redaxo/redaxo5_x_demoaddon/redaxo/src/addons/yform_field/lib/yform/value/select.php(25): explode()
#2 /usr/local/www/redaxo/redaxo5_x_demoaddon/redaxo/src/addons/yform/lib/yform.php(368): rex_yform_value_select->enterObject()
#3 /usr/local/www/redaxo/redaxo5_x_demoaddon/redaxo/src/addons/yform/lib/yform.php(269): rex_yform->executeFields()
#4 /usr/local/www/redaxo/redaxo5_x_demoaddon/redaxo/src/addons/yform/plugins/manager/lib/yform/manager/search.php(86): rex_yform->getForm()
#5 /usr/local/www/redaxo/redaxo5_x_demoaddon/redaxo/src/addons/yform/plugins/manager/lib/yform/manager.php(125): rex_yform_manager_search->getForm()
#6 /usr/local/www/redaxo/redaxo5_x_demoaddon/redaxo/src/addons/yform/plugins/manager/pages/data_edit.php(20): rex_yform_manager->getDataPage()
#7 /usr/local/www/redaxo/redaxo5_x_demoaddon/redaxo/src/addons/neues/pages/data_edit.php(29): include('...')
#8 /usr/local/www/redaxo/redaxo5_x_demoaddon/redaxo/src/core/lib/packages/package.php(233): require('...')
#9 /usr/local/www/redaxo/redaxo5_x_demoaddon/redaxo/src/core/lib/be/controller.php(503): rex_package->includeFile()
#10 /usr/local/www/redaxo/redaxo5_x_demoaddon/redaxo/src/core/lib/util/timer.php(62): rex_be_controller::{closure}()
#11 /usr/local/www/redaxo/redaxo5_x_demoaddon/redaxo/src/core/lib/be/controller.php(485): rex_timer::measure()
#12 /usr/local/www/redaxo/redaxo5_x_demoaddon/redaxo/src/core/lib/be/controller.php(453): rex_be_controller::includePath()
#13 /usr/local/www/redaxo/redaxo5_x_demoaddon/redaxo/src/addons/neues/pages/neues.php(4): rex_be_controller::includeCurrentPageSubPath()
#14 /usr/local/www/redaxo/redaxo5_x_demoaddon/redaxo/src/core/lib/packages/package.php(233): require('...')
#15 /usr/local/www/redaxo/redaxo5_x_demoaddon/redaxo/src/core/lib/be/controller.php(503): rex_package->includeFile()
#16 /usr/local/www/redaxo/redaxo5_x_demoaddon/redaxo/src/core/lib/util/timer.php(62): rex_be_controller::{closure}()
#17 /usr/local/www/redaxo/redaxo5_x_demoaddon/redaxo/src/core/lib/be/controller.php(485): rex_timer::measure()
#18 /usr/local/www/redaxo/redaxo5_x_demoaddon/redaxo/src/core/lib/be/controller.php(436): rex_be_controller::includePath()
#19 /usr/local/www/redaxo/redaxo5_x_demoaddon/redaxo/src/core/backend.php(241): rex_be_controller::includeCurrentPage()
#20 /usr/local/www/redaxo/redaxo5_x_demoaddon/redaxo/src/core/boot.php(155): require('...')
#21 /usr/local/www/redaxo/redaxo5_x_demoaddon/redaxo/index.php(9): require('...')
#22 {main}
```

**Comment by alxndr-w** [comment]
Danke, schau ich mir an! 

Kann es sein, dass in meinem oder einem anderen Add-on ein altes select-Feld in der Felddefinition rumgeistert?

Das kommt aus Abwärts-Kompatibilitätsgründen in YForm Field mit, sollte aber nicht mehr in meinen Add-ons oder generell verwendet werden.

**Comment by alxndr-w** [comment]
https://github.com/alexplusde/yform_field

Das müsste hier gelöst werden meines Erachtens.

**Comment by alxndr-w** [comment]
@Koala teste doch bitte mal das aktualisierte select-Value und schreib mir, welches Feld in `neues` noch ein klassisches Select einsetzt bitte.

**Comment by Koala** [comment]
Heurika, es funktoniert.

Bei "Eintrag" auf das "+" geklickt bringt mir allerdings:

![grafik](https://github.com/alexplusde/neues/assets/330686/6a9ff9b5-37aa-44dc-86ea-cb469d0a6b4c)

**Comment by Koala** [comment]
https://github.com/alexplusde/yform_field/blob/dc3a55d66a26d6e226553f16059305ee1b7b7727/lib/yform/value/domain.php#L24

`            $values = explode(',', $values ?? '');`

Ich fürchte, dass braucht es bei allen *explodes*.

**Comment by alxndr-w** [comment]
@Koala wenn du das schon so auf dem Schirm hast und dazu einen PR machen würdest und die `explode()` stellen damit übergangsweise gefixt wären, wäre auch das mir eine Hilfe. 

Ich würde es sonst erst machen, wenn ich selbst das Problem habe.
